2020 update: rules and fees
ssheikholeslami/EIT-Digital-In-Farsi pull request #13
Opened 2020-04-27 21:31 UTC by HsnFirooz

I updated the Programs list, 2020 Tuition fees, application process based on the new rules, and added a few tips in the application section.
Thanks for your awesome guide, Sina!

2020-04-29 20:14 UTC, ssheikholeslami requested changes
خیلی مرسی حسین جان

2020-04-29 20:14 UTC, ssheikholeslami commented on README.md
> +* Digital Manufactaring
Digital Manufacturing

2020-04-29 20:14 UTC, ssheikholeslami commented on README.md
> +یه مزیت دیگه‌ی اقدام کردن در بازه اول اینه که شما میتونین برای دوتا پروگرام اقدام کنید. البته باید برای هر دو تا SOP جداگانه بنویسید ولی مثلا توصیه‌نامه‌هاتون برای هر دوتا برنامه محسوب میشن. البته دق
اولویت

2020-04-29 20:14 UTC, ssheikholeslami commented on README.md
> +هزینه ثبت‌نام رو باید قبل از شروع هر ترم پرداخت کنین. این شهریه تغییر میکنه و این لینک مقدار دقیقش مشخصه. زمان ادیت این فایل (سال ۲۰۲۰) شهریه برای هر ترم ۶۰۰۰ یوروه.
کدوم لینک؟

2020-04-30 19:36 UTC, HsnFirooz commented on README.md
> +یه مزیت دیگه‌ی اقدام کردن در بازه اول اینه که شما میتونین برای دوتا پروگرام اقدام کنید. البته باید برای هر دو تا SOP جداگانه بنویسید ولی مثلا توصیه‌نامه‌هاتون برای هر دوتا برنامه محسوب میشن. البته دق
این رو واقعا نمیدونستم! فکر میکردم الویت نوشته میشه :‌))

2020-04-30 19:36 UTC, HsnFirooz commented on README.md
> +* Digital Manufactaring
Sorry, my bad.

2020-04-30 19:53 UTC, HsnFirooz commented on README.md
> +* Digital Manufactaring
Fixed on 2623995864caea8c50c1602e1265a45273939fa5

2020-04-30 19:53 UTC, HsnFirooz commented on README.md
> +یه مزیت دیگه‌ی اقدام کردن در بازه اول اینه که شما میتونین برای دوتا پروگرام اقدام کنید. البته باید برای هر دو تا SOP جداگانه بنویسید ولی مثلا توصیه‌نامه‌هاتون برای هر دوتا برنامه محسوب میشن. البته دق
Fixed on 2623995864caea8c50c1602e1265a45273939fa5

2020-04-30 19:54 UTC, HsnFirooz commented on README.md
> +هزینه ثبت‌نام رو باید قبل از شروع هر ترم پرداخت کنین. این شهریه تغییر میکنه و این لینک مقدار دقیقش مشخصه. زمان ادیت این فایل (سال ۲۰۲۰) شهریه برای هر ترم ۶۰۰۰ یوروه.
ظاهرا فراموش کردم لینک رو بذارم. یه "در" هم کم داشته البته.
Fixed on 2623995864caea8c50c1602e1265a45273939fa5

2020-05-02 11:54 UTC, ssheikholeslami approved these changes

2020-05-02 11:55 UTC, merged